### ISSUE TITLE
Mbed-simulator is not compatible with Windows 10

### ISSUE THREAD

**Issue by woobagooba** [janjongboom/mbed-simulator#32] opened 2019-04-09 20:49 UTC
First, thank you for this work.  We see value in it ... if we can get past our local build and run troubles.  

Why a local build and install?  To operate mbed-simulator with NS other than TTN.  

There are two sets of build instructions with are sparse, differ, overlap, and will not work for us.
Here (https://os.mbed.com/blog/entry/introducing-mbed-simulator/)  "Offline" and here  (https://github.com/janjongboom/mbed-simulator) 

The latter instruction set directs to install "recent" version of node ... ?
Mbed CLI pulls in its version of Python.
Emscriptem pulls in its own version of Node and Python.
We are getting runtime errors that Mbed CLI is not installed ... it is.

Much appreciated and useful to the general community if could Docker-ize mbed-simulator ... a useful Quick Start.

**Comment by woobagooba** [comment] 2019-04-10 01:55
![image](https://user-images.githubusercontent.com/3648022/55845966-fa189f00-5b11-11e9-9e44-3d6830c833f1.png)

Windows indicated Mbed CLI is installed.

**Comment by woobagooba** [comment] 2019-04-10 18:21
Further update (as we are working to provide a set of corrected install instructions ) ...

For some unknown reason, Mbed CLI will not install on a particular Win 10 system.  Separate issue has been opened.  https://github.com/ARMmbed/mbed-cli/issues/883

We are able to install Mbed CLI on a different Win 10 system.  We have worked the install through to the point that the mbed-simulator demo builds (all of them) fail as the libmbed build fails due to Windows Error 206 ... filename to long.

Please advise next steps.

**Comment by j3hill** [comment] 2019-04-11 14:54
@woobagooba I've been able to reproduce this issue with a "clean" Windows 10 install (64-bit), after applying all updates. As noted in this issue: https://github.com/ARMmbed/mbed-cli/issues/883 you can manually fix the problem by running "pip install mbed-cli".

**Comment by woobagooba** [comment] 2019-04-11 19:23
@j3hill do you mean "pip install mbed-cli" resolves the mbed not installing issue?  Or do you mean it also fixes the Mbed OS simulator compilation issue?  I assume you mean the former, which means there is still a stopper issue with the compilation failures.

**Comment by woobagooba** [comment] 2019-04-15 16:36
New week, fresh start, no joy.

Removed the entirety of previous Mbed OS sim install, including Mbed CLI and Emscriptem.
Made sure long filenames are enabled on Win10.  Restarted.
Fresh install of Mbed OS sim (including Mbed CLI and Emscriptem)
Install fails at the demo build step.
libmbed will not build, windows 206 error thrown by emcc/python.
Best we can determine, the only way around this is to use python 3.6 or later.
We are therefore left with the conclusion that Mbed OS sim is not compatible with Win 10.

**Comment by janjongboom** [comment] 2019-04-16 02:58
@woobagooba Thanks for reporting. I've used the simulator in Windows in the past, but main development is on macOS and Linux, so haven't used it recently. Based on the error I assume you're overrunning the 259 character limit for file names which exists in Windows. Which folder have you installed the simulator in? Is it possible to move it to a location where the total file name will be lower (e.g. throw it in `C:`?). Alternatively, I think Cygwin does not have the file name limit, that would be an option.

> Why a local build and install? To operate mbed-simulator with NS other than TTN.

See my comment in https://github.com/janjongboom/mbed-simulator/issues/30#issuecomment-480815636

> There are two sets of build instructions with are sparse, differ, overlap, and will not work for us.

Use the version in README in this repository for reference.

**Comment by woobagooba** [comment] 2019-04-16 03:18
https://github.com/emscripten-core/emscripten/issues/8442

**Comment by janjongboom** [comment] 2019-04-26 10:05
Alright, I've found the issues and have pushed a fix here: https://github.com/janjongboom/mbed-simulator/pull/33. The new release is 1.9.5. Thanks for reporting again!

**Closed by janjongboom** 2019-04-26 10:05 UTC

**Comment by woobagooba** [comment] 2019-04-26 22:54
Thanks Jan

Your install instructions need to be consolidated into a single place and verified for correctness.

**Comment by woobagooba** [comment] 2019-04-29 20:20
Please  re-open

![Capture](https://user-images.githubusercontent.com/3648022/56924346-ace97680-6a9a-11e9-9158-b737387d1c7b.PNG)

**Comment by woobagooba** [comment] 2019-04-30 13:25
I'm moving this to a new thread

**Comment by knish82** [comment] 2020-04-24 14:00
Dear @woobagooba please, can you say which version of Emscripten are you using? I'm trying to install mbed simulator offline, but it doens't work. I obtain a fatal error, probably due to the last version of emcc. At present time, the version reccomended by   janjongboom is not present anymore.

**Comment by woobagooba** [comment] 2020-04-24 16:02
Sorry, but my team long ago gave up on Emscripten and Mbed Simulator.

Too much time spent fighting with the build issues.

**Comment by knish82** [comment] 2020-04-24 16:05
I understand your point, thank you for your reply. So, did you find some other alternative to offline mbed simulator? 
Thank you again @woobagooba
